//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoogleClient.BoggleServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountDTO", Namespace="http://schemas.datacontract.org/2004/07/BoggleModel.DataTransfer.Dtos")]
    [System.SerializableAttribute()]
    public partial class AccountDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LobbySettingsDTO", Namespace="http://schemas.datacontract.org/2004/07/BoggleModel.DataTransfer.Dtos")]
    [System.SerializableAttribute()]
    public partial class LobbySettingsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatorUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GameModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LobbyPrivacyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfPlayersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatorUserName {
            get {
                return this.CreatorUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatorUserNameField, value) != true)) {
                    this.CreatorUserNameField = value;
                    this.RaisePropertyChanged("CreatorUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameMode {
            get {
                return this.GameModeField;
            }
            set {
                if ((object.ReferenceEquals(this.GameModeField, value) != true)) {
                    this.GameModeField = value;
                    this.RaisePropertyChanged("GameMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LobbyPrivacy {
            get {
                return this.LobbyPrivacyField;
            }
            set {
                if ((object.ReferenceEquals(this.LobbyPrivacyField, value) != true)) {
                    this.LobbyPrivacyField = value;
                    this.RaisePropertyChanged("LobbyPrivacy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfPlayers {
            get {
                return this.NumberOfPlayersField;
            }
            set {
                if ((this.NumberOfPlayersField.Equals(value) != true)) {
                    this.NumberOfPlayersField = value;
                    this.RaisePropertyChanged("NumberOfPlayers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lobby", Namespace="http://schemas.datacontract.org/2004/07/BoggleModel")]
    [System.SerializableAttribute()]
    public partial class Lobby : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoogleClient.BoggleServices.Match GameMatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoogleClient.BoggleServices.Message[] MessageHistoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoogleClient.BoggleServices.Player[] PlayersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrivacyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BoogleClient.BoggleServices.Match GameMatch {
            get {
                return this.GameMatchField;
            }
            set {
                if ((object.ReferenceEquals(this.GameMatchField, value) != true)) {
                    this.GameMatchField = value;
                    this.RaisePropertyChanged("GameMatch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Host {
            get {
                return this.HostField;
            }
            set {
                if ((object.ReferenceEquals(this.HostField, value) != true)) {
                    this.HostField = value;
                    this.RaisePropertyChanged("Host");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BoogleClient.BoggleServices.Message[] MessageHistory {
            get {
                return this.MessageHistoryField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageHistoryField, value) != true)) {
                    this.MessageHistoryField = value;
                    this.RaisePropertyChanged("MessageHistory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BoogleClient.BoggleServices.Player[] Players {
            get {
                return this.PlayersField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayersField, value) != true)) {
                    this.PlayersField = value;
                    this.RaisePropertyChanged("Players");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Privacy {
            get {
                return this.PrivacyField;
            }
            set {
                if ((object.ReferenceEquals(this.PrivacyField, value) != true)) {
                    this.PrivacyField = value;
                    this.RaisePropertyChanged("Privacy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Size {
            get {
                return this.SizeField;
            }
            set {
                if ((this.SizeField.Equals(value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Match", Namespace="http://schemas.datacontract.org/2004/07/BoggleModel")]
    [System.SerializableAttribute()]
    public partial class Match : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GameModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoogleClient.BoggleServices.Board MatchBoardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoundsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecondsPerRoundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WinningScoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameMode {
            get {
                return this.GameModeField;
            }
            set {
                if ((object.ReferenceEquals(this.GameModeField, value) != true)) {
                    this.GameModeField = value;
                    this.RaisePropertyChanged("GameMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BoogleClient.BoggleServices.Board MatchBoard {
            get {
                return this.MatchBoardField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchBoardField, value) != true)) {
                    this.MatchBoardField = value;
                    this.RaisePropertyChanged("MatchBoard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rounds {
            get {
                return this.RoundsField;
            }
            set {
                if ((this.RoundsField.Equals(value) != true)) {
                    this.RoundsField = value;
                    this.RaisePropertyChanged("Rounds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecondsPerRound {
            get {
                return this.SecondsPerRoundField;
            }
            set {
                if ((this.SecondsPerRoundField.Equals(value) != true)) {
                    this.SecondsPerRoundField = value;
                    this.RaisePropertyChanged("SecondsPerRound");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WinningScore {
            get {
                return this.WinningScoreField;
            }
            set {
                if ((this.WinningScoreField.Equals(value) != true)) {
                    this.WinningScoreField = value;
                    this.RaisePropertyChanged("WinningScore");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/BoggleModel")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeSentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeSent {
            get {
                return this.TimeSentField;
            }
            set {
                if ((this.TimeSentField.Equals(value) != true)) {
                    this.TimeSentField = value;
                    this.RaisePropertyChanged("TimeSent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/BoggleModel")]
    [System.SerializableAttribute()]
    public partial class Player : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoogleClient.BoggleServices.UserAccount AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoogleClient.BoggleServices.FriendRequest[] FriendRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoogleClient.BoggleServices.PerformanceRecord PerformanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BoogleClient.BoggleServices.UserAccount Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BoogleClient.BoggleServices.FriendRequest[] FriendRequests {
            get {
                return this.FriendRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.FriendRequestsField, value) != true)) {
                    this.FriendRequestsField = value;
                    this.RaisePropertyChanged("FriendRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nationality {
            get {
                return this.NationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalityField, value) != true)) {
                    this.NationalityField = value;
                    this.RaisePropertyChanged("Nationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BoogleClient.BoggleServices.PerformanceRecord Performance {
            get {
                return this.PerformanceField;
            }
            set {
                if ((object.ReferenceEquals(this.PerformanceField, value) != true)) {
                    this.PerformanceField = value;
                    this.RaisePropertyChanged("Performance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Board", Namespace="http://schemas.datacontract.org/2004/07/BoggleModel")]
    [System.SerializableAttribute()]
    public partial class Board : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoogleClient.BoggleServices.Dice[] DicesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BoogleClient.BoggleServices.Dice[] Dices {
            get {
                return this.DicesField;
            }
            set {
                if ((object.ReferenceEquals(this.DicesField, value) != true)) {
                    this.DicesField = value;
                    this.RaisePropertyChanged("Dices");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dice", Namespace="http://schemas.datacontract.org/2004/07/BoggleModel")]
    [System.SerializableAttribute()]
    public partial class Dice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] FacesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Faces {
            get {
                return this.FacesField;
            }
            set {
                if ((object.ReferenceEquals(this.FacesField, value) != true)) {
                    this.FacesField = value;
                    this.RaisePropertyChanged("Faces");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAccount", Namespace="http://schemas.datacontract.org/2004/07/BoggleModel")]
    [System.SerializableAttribute()]
    public partial class UserAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsVerifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoogleClient.BoggleServices.Player PlayerAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsVerified {
            get {
                return this.IsVerifiedField;
            }
            set {
                if ((this.IsVerifiedField.Equals(value) != true)) {
                    this.IsVerifiedField = value;
                    this.RaisePropertyChanged("IsVerified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BoogleClient.BoggleServices.Player PlayerAccount {
            get {
                return this.PlayerAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerAccountField, value) != true)) {
                    this.PlayerAccountField = value;
                    this.RaisePropertyChanged("PlayerAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerformanceRecord", Namespace="http://schemas.datacontract.org/2004/07/BoggleModel")]
    [System.SerializableAttribute()]
    public partial class PerformanceRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoogleClient.BoggleServices.Player PlayerPerformanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BoogleClient.BoggleServices.Player PlayerPerformance {
            get {
                return this.PlayerPerformanceField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerPerformanceField, value) != true)) {
                    this.PlayerPerformanceField = value;
                    this.RaisePropertyChanged("PlayerPerformance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendRequest", Namespace="http://schemas.datacontract.org/2004/07/BoggleModel")]
    [System.SerializableAttribute()]
    public partial class FriendRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoogleClient.BoggleServices.Player ReceiverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoogleClient.BoggleServices.Player SenderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BoogleClient.BoggleServices.Player Receiver {
            get {
                return this.ReceiverField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverField, value) != true)) {
                    this.ReceiverField = value;
                    this.RaisePropertyChanged("Receiver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BoogleClient.BoggleServices.Player Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PublicLobbyPreviewDTO", Namespace="http://schemas.datacontract.org/2004/07/BoggleModel.DataTransfer.Dtos")]
    [System.SerializableAttribute()]
    public partial class PublicLobbyPreviewDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GameModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LobbyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LobbySizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlayersInsideField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameMode {
            get {
                return this.GameModeField;
            }
            set {
                if ((object.ReferenceEquals(this.GameModeField, value) != true)) {
                    this.GameModeField = value;
                    this.RaisePropertyChanged("GameMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LobbyCode {
            get {
                return this.LobbyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LobbyCodeField, value) != true)) {
                    this.LobbyCodeField = value;
                    this.RaisePropertyChanged("LobbyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LobbySize {
            get {
                return this.LobbySizeField;
            }
            set {
                if ((this.LobbySizeField.Equals(value) != true)) {
                    this.LobbySizeField = value;
                    this.RaisePropertyChanged("LobbySize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayersInside {
            get {
                return this.PlayersInsideField;
            }
            set {
                if ((this.PlayersInsideField.Equals(value) != true)) {
                    this.PlayersInsideField = value;
                    this.RaisePropertyChanged("PlayersInside");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BoggleServices.IUserManagerContract", CallbackContract=typeof(BoogleClient.BoggleServices.IUserManagerContractCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IUserManagerContract {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserManagerContract/LogIn")]
        void LogIn(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserManagerContract/LogIn")]
        System.Threading.Tasks.Task LogInAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserManagerContract/LogOut")]
        void LogOut(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserManagerContract/LogOut")]
        System.Threading.Tasks.Task LogOutAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserManagerContract/CreateAccount")]
        void CreateAccount(BoogleClient.BoggleServices.AccountDTO accountDTO);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserManagerContract/CreateAccount")]
        System.Threading.Tasks.Task CreateAccountAsync(BoogleClient.BoggleServices.AccountDTO accountDTO);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserManagerContract/ValidateEmail")]
        void ValidateEmail(string validationCode, string email);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserManagerContract/ValidateEmail")]
        System.Threading.Tasks.Task ValidateEmailAsync(string validationCode, string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserManagerContractCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerContract/GrantAccess", ReplyAction="http://tempuri.org/IUserManagerContract/GrantAccessResponse")]
        void GrantAccess(string accessStatus, BoogleClient.BoggleServices.AccountDTO accountInfoDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerContract/CloseSession", ReplyAction="http://tempuri.org/IUserManagerContract/CloseSessionResponse")]
        void CloseSession();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerContract/AskForEmailValidation", ReplyAction="http://tempuri.org/IUserManagerContract/AskForEmailValidationResponse")]
        void AskForEmailValidation(string accountCreationStatus, string userEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerContract/GrantValidation", ReplyAction="http://tempuri.org/IUserManagerContract/GrantValidationResponse")]
        void GrantValidation(string validationStatus, BoogleClient.BoggleServices.AccountDTO accountInfoDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerContract/DeliverLobbyInvite", ReplyAction="http://tempuri.org/IUserManagerContract/DeliverLobbyInviteResponse")]
        void DeliverLobbyInvite(string lobbyCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserManagerContractChannel : BoogleClient.BoggleServices.IUserManagerContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserManagerContractClient : System.ServiceModel.DuplexClientBase<BoogleClient.BoggleServices.IUserManagerContract>, BoogleClient.BoggleServices.IUserManagerContract {
        
        public UserManagerContractClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public UserManagerContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public UserManagerContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagerContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagerContractClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void LogIn(string userName, string password) {
            base.Channel.LogIn(userName, password);
        }
        
        public System.Threading.Tasks.Task LogInAsync(string userName, string password) {
            return base.Channel.LogInAsync(userName, password);
        }
        
        public void LogOut(string username) {
            base.Channel.LogOut(username);
        }
        
        public System.Threading.Tasks.Task LogOutAsync(string username) {
            return base.Channel.LogOutAsync(username);
        }
        
        public void CreateAccount(BoogleClient.BoggleServices.AccountDTO accountDTO) {
            base.Channel.CreateAccount(accountDTO);
        }
        
        public System.Threading.Tasks.Task CreateAccountAsync(BoogleClient.BoggleServices.AccountDTO accountDTO) {
            return base.Channel.CreateAccountAsync(accountDTO);
        }
        
        public void ValidateEmail(string validationCode, string email) {
            base.Channel.ValidateEmail(validationCode, email);
        }
        
        public System.Threading.Tasks.Task ValidateEmailAsync(string validationCode, string email) {
            return base.Channel.ValidateEmailAsync(validationCode, email);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BoggleServices.IGameManagerContract", CallbackContract=typeof(BoogleClient.BoggleServices.IGameManagerContractCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IGameManagerContract {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagerContract/CreateLobby")]
        void CreateLobby(BoogleClient.BoggleServices.LobbySettingsDTO lobbySettings);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagerContract/CreateLobby")]
        System.Threading.Tasks.Task CreateLobbyAsync(BoogleClient.BoggleServices.LobbySettingsDTO lobbySettings);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagerContract/AskToJoinLobby")]
        void AskToJoinLobby(string userName, string lobbyCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagerContract/AskToJoinLobby")]
        System.Threading.Tasks.Task AskToJoinLobbyAsync(string userName, string lobbyCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagerContract/SearchPublicLobbies")]
        void SearchPublicLobbies();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagerContract/SearchPublicLobbies")]
        System.Threading.Tasks.Task SearchPublicLobbiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagerContract/UpdatePublicLobbies")]
        void UpdatePublicLobbies();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagerContract/UpdatePublicLobbies")]
        System.Threading.Tasks.Task UpdatePublicLobbiesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameManagerContractCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManagerContract/GrantAccessToJoinLobby", ReplyAction="http://tempuri.org/IGameManagerContract/GrantAccessToJoinLobbyResponse")]
        void GrantAccessToJoinLobby(BoogleClient.BoggleServices.Lobby lobby);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManagerContract/DisplayPublicLobbies", ReplyAction="http://tempuri.org/IGameManagerContract/DisplayPublicLobbiesResponse")]
        void DisplayPublicLobbies(BoogleClient.BoggleServices.PublicLobbyPreviewDTO[] publicLobbies);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManagerContract/RefreshPublicLobbies", ReplyAction="http://tempuri.org/IGameManagerContract/RefreshPublicLobbiesResponse")]
        void RefreshPublicLobbies(BoogleClient.BoggleServices.PublicLobbyPreviewDTO[] publicLobbies);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameManagerContractChannel : BoogleClient.BoggleServices.IGameManagerContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameManagerContractClient : System.ServiceModel.DuplexClientBase<BoogleClient.BoggleServices.IGameManagerContract>, BoogleClient.BoggleServices.IGameManagerContract {
        
        public GameManagerContractClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GameManagerContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GameManagerContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameManagerContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameManagerContractClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void CreateLobby(BoogleClient.BoggleServices.LobbySettingsDTO lobbySettings) {
            base.Channel.CreateLobby(lobbySettings);
        }
        
        public System.Threading.Tasks.Task CreateLobbyAsync(BoogleClient.BoggleServices.LobbySettingsDTO lobbySettings) {
            return base.Channel.CreateLobbyAsync(lobbySettings);
        }
        
        public void AskToJoinLobby(string userName, string lobbyCode) {
            base.Channel.AskToJoinLobby(userName, lobbyCode);
        }
        
        public System.Threading.Tasks.Task AskToJoinLobbyAsync(string userName, string lobbyCode) {
            return base.Channel.AskToJoinLobbyAsync(userName, lobbyCode);
        }
        
        public void SearchPublicLobbies() {
            base.Channel.SearchPublicLobbies();
        }
        
        public System.Threading.Tasks.Task SearchPublicLobbiesAsync() {
            return base.Channel.SearchPublicLobbiesAsync();
        }
        
        public void UpdatePublicLobbies() {
            base.Channel.UpdatePublicLobbies();
        }
        
        public System.Threading.Tasks.Task UpdatePublicLobbiesAsync() {
            return base.Channel.UpdatePublicLobbiesAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BoggleServices.ILobbyManagerContract", CallbackContract=typeof(BoogleClient.BoggleServices.ILobbyManagerContractCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ILobbyManagerContract {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManagerContract/JoinLobby")]
        void JoinLobby(string userName, string lobbyCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManagerContract/JoinLobby")]
        System.Threading.Tasks.Task JoinLobbyAsync(string userName, string lobbyCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManagerContract/ExitLobby")]
        void ExitLobby(string userName, string lobbyCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManagerContract/ExitLobby")]
        System.Threading.Tasks.Task ExitLobbyAsync(string userName, string lobbyCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManagerContract/SendMessage")]
        void SendMessage(BoogleClient.BoggleServices.Lobby lobby, string body, string sender);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManagerContract/SendMessage")]
        System.Threading.Tasks.Task SendMessageAsync(BoogleClient.BoggleServices.Lobby lobby, string body, string sender);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManagerContract/SendInvite")]
        void SendInvite(BoogleClient.BoggleServices.Lobby lobby, string sender, string receiver);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManagerContract/SendInvite")]
        System.Threading.Tasks.Task SendInviteAsync(BoogleClient.BoggleServices.Lobby lobby, string sender, string receiver);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManagerContract/ChangeMatchSettings")]
        void ChangeMatchSettings(BoogleClient.BoggleServices.Lobby lobby);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManagerContract/ChangeMatchSettings")]
        System.Threading.Tasks.Task ChangeMatchSettingsAsync(BoogleClient.BoggleServices.Lobby lobby);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILobbyManagerContractCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManagerContract/UpdateLobby", ReplyAction="http://tempuri.org/ILobbyManagerContract/UpdateLobbyResponse")]
        void UpdateLobby(BoogleClient.BoggleServices.Lobby lobby);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILobbyManagerContractChannel : BoogleClient.BoggleServices.ILobbyManagerContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LobbyManagerContractClient : System.ServiceModel.DuplexClientBase<BoogleClient.BoggleServices.ILobbyManagerContract>, BoogleClient.BoggleServices.ILobbyManagerContract {
        
        public LobbyManagerContractClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public LobbyManagerContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public LobbyManagerContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LobbyManagerContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LobbyManagerContractClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void JoinLobby(string userName, string lobbyCode) {
            base.Channel.JoinLobby(userName, lobbyCode);
        }
        
        public System.Threading.Tasks.Task JoinLobbyAsync(string userName, string lobbyCode) {
            return base.Channel.JoinLobbyAsync(userName, lobbyCode);
        }
        
        public void ExitLobby(string userName, string lobbyCode) {
            base.Channel.ExitLobby(userName, lobbyCode);
        }
        
        public System.Threading.Tasks.Task ExitLobbyAsync(string userName, string lobbyCode) {
            return base.Channel.ExitLobbyAsync(userName, lobbyCode);
        }
        
        public void SendMessage(BoogleClient.BoggleServices.Lobby lobby, string body, string sender) {
            base.Channel.SendMessage(lobby, body, sender);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(BoogleClient.BoggleServices.Lobby lobby, string body, string sender) {
            return base.Channel.SendMessageAsync(lobby, body, sender);
        }
        
        public void SendInvite(BoogleClient.BoggleServices.Lobby lobby, string sender, string receiver) {
            base.Channel.SendInvite(lobby, sender, receiver);
        }
        
        public System.Threading.Tasks.Task SendInviteAsync(BoogleClient.BoggleServices.Lobby lobby, string sender, string receiver) {
            return base.Channel.SendInviteAsync(lobby, sender, receiver);
        }
        
        public void ChangeMatchSettings(BoogleClient.BoggleServices.Lobby lobby) {
            base.Channel.ChangeMatchSettings(lobby);
        }
        
        public System.Threading.Tasks.Task ChangeMatchSettingsAsync(BoogleClient.BoggleServices.Lobby lobby) {
            return base.Channel.ChangeMatchSettingsAsync(lobby);
        }
    }
}
