//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoogleClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoogleClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Friend.
        /// </summary>
        public static string addFriend {
            get {
                return ResourceManager.GetString("addFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics.
        /// </summary>
        public static string analytics {
            get {
                return ResourceManager.GetString("analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcade.
        /// </summary>
        public static string arcade {
            get {
                return ResourceManager.GetString("arcade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        public static string classic {
            get {
                return ResourceManager.GetString("classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve sent a validation code to your email. Type your code in the textfield below to validate your account..
        /// </summary>
        public static string codeSentMessage {
            get {
                return ResourceManager.GetString("codeSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string confirmPassword {
            get {
                return ResourceManager.GetString("confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string createAccount {
            get {
                return ResourceManager.GetString("createAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Lobby.
        /// </summary>
        public static string createLobby {
            get {
                return ResourceManager.GetString("createLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Lobby.
        /// </summary>
        public static string exitLobby {
            get {
                return ResourceManager.GetString("exitLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string forgotPassword {
            get {
                return ResourceManager.GetString("forgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Code.
        /// </summary>
        public static string friendCode {
            get {
                return ResourceManager.GetString("friendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game mode.
        /// </summary>
        public static string gameMode {
            get {
                return ResourceManager.GetString("gameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Played.
        /// </summary>
        public static string gamesPlayed {
            get {
                return ResourceManager.GetString("gamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Score.
        /// </summary>
        public static string highestScore {
            get {
                return ResourceManager.GetString("highestScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Player.
        /// </summary>
        public static string invitePlayer {
            get {
                return ResourceManager.GetString("invitePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string join {
            get {
                return ResourceManager.GetString("join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Lobby.
        /// </summary>
        public static string joinLobby {
            get {
                return ResourceManager.GetString("joinLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboard.
        /// </summary>
        public static string leaderboard {
            get {
                return ResourceManager.GetString("leaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby Privacy.
        /// </summary>
        public static string lobbyPrivacy {
            get {
                return ResourceManager.GetString("lobbyPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string logIn {
            get {
                return ResourceManager.GetString("logIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match History.
        /// </summary>
        public static string matchHistory {
            get {
                return ResourceManager.GetString("matchHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Settings.
        /// </summary>
        public static string matchSettings {
            get {
                return ResourceManager.GetString("matchSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match starting in....
        /// </summary>
        public static string matchStarting {
            get {
                return ResourceManager.GetString("matchStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of players.
        /// </summary>
        public static string numberOfPlayers {
            get {
                return ResourceManager.GetString("numberOfPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string online {
            get {
                return ResourceManager.GetString("online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string overview {
            get {
                return ResourceManager.GetString("overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players in lobby.
        /// </summary>
        public static string playersInLobby {
            get {
                return ResourceManager.GetString("playersInLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players invited.
        /// </summary>
        public static string playersInvited {
            get {
                return ResourceManager.GetString("playersInvited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Lobby Code.
        /// </summary>
        public static string privateLobbyCode {
            get {
                return ResourceManager.GetString("privateLobbyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        public static string race {
            get {
                return ResourceManager.GetString("race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string requests {
            get {
                return ResourceManager.GetString("requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search public lobby.
        /// </summary>
        public static string searchPublicLobby {
            get {
                return ResourceManager.GetString("searchPublicLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send code again.
        /// </summary>
        public static string sendCodeAgain {
            get {
                return ResourceManager.GetString("sendCodeAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socials.
        /// </summary>
        public static string socials {
            get {
                return ResourceManager.GetString("socials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Score.
        /// </summary>
        public static string totalScore {
            get {
                return ResourceManager.GetString("totalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate email.
        /// </summary>
        public static string validateEmail {
            get {
                return ResourceManager.GetString("validateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victories.
        /// </summary>
        public static string victories {
            get {
                return ResourceManager.GetString("victories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your message....
        /// </summary>
        public static string writeYourMessage {
            get {
                return ResourceManager.GetString("writeYourMessage", resourceCulture);
            }
        }
    }
}
